// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vamber48_core_branch_tb.cpp"
#include "Vamber48_core_branch_tb___024root__DepSet_h47994b59__0.cpp"
#include "Vamber48_core_branch_tb___024root__DepSet_hbdfa2687__0.cpp"
#include "Vamber48_core_branch_tb__main.cpp"
#include "Vamber48_core_branch_tb__ConstPool_0.cpp"
#include "Vamber48_core_branch_tb___024root__Slow.cpp"
#include "Vamber48_core_branch_tb___024root__DepSet_h47994b59__0__Slow.cpp"
#include "Vamber48_core_branch_tb___024root__DepSet_hbdfa2687__0__Slow.cpp"
#include "Vamber48_core_branch_tb__Syms.cpp"
